Emplea-do/emplea_do

AppService/Services/JobService.cs, Web/Controllers/JobsController.cs, Web/Views/Jobs/Detail.cshtml, Web/Views/Jobs/Wizard.cshtml
In this update, the user will be able to Edit their posted jobs. The user is allowed its own jobs or will be redirected to the home page notifying that he/she can't update the job or that the job is invalid.
After a job is edited, should be approved again by staff, so a notification is sent to the slack channel.
No visual aids
=> Implement Edit Job process on Emplea.do page

Data/Repositories/BaseRepository.cs, Web/Controllers/JobsController.cs, Web/Views/Jobs/Detail.cshtml, Web/Views/Jobs/_Partials/ConfirmDeleteModal.cshtml
Added the delete job behavior on the Job's detail page. This behavior makes a Soft Delete on the Job registry in the database; which means that adds the DeleteAt date value and sets IsActive to false.
_No visual aids_
=> Added delete job behavior

Readme.md
Here the URLs from the Readme.md are in correct order.
Thanks for the support @eatskolnikov!
=> URLs from Readme.md fixed

AppServices/Services/JobsService.cs
Fix compiler Issues: Delete duplicate properties in the `JobService` class in the project `App Services`, and format the class for a better readability.
=> Delete duplicate properties

Web/Framework/Configurations/AuthConfiguration.cs, Web/appsettings.Development.json, Web/appsettings.template.json
- Now we can Sign In and Log In using GitHub
- Format json file for better readability
**Signing in with GitHub:**  
**Already Logged In:** 
**List of registered users in the application with GitHub:**
This closes #49, closes #70
=> GitHub authentication

Migrations/201909062116_adding_category_tbl.cs, Migrations/201909090017_inserting_category_and_hiretype_data.cs
- Changed the datatype of the Name column for the Categories table to String.
=> Categories table's name column data type was incorrect.

Web/Views/Shared/_Layout.cshtml
- List your changes in a concise and clear way
- This will give the reviewers an idea of where to look for smelly code
If there are visual changes include them here. You can add a screenshot or a recording using a tool like [this one](https://recordit.co/) and include it in the Pull Request.
This is the markdown to include an image in the pull request:
```md
```
You can include a comparison table as follows:
|---|---|
| Insert images from before the fix | Here is the after |
=> Fixed stuff

AppServices/Services/TwitterService.cs, Web/Controllers/JobsController.cs, Web/Startup.cs, Web/appsettings.template.json
related to #50 
- added twitterServices class for manage request to twitter api
- modify appsetting.template.json to add twitter config section 
-added method call using task in JobsController.Wizard
must be added the twitter configuration in appsetting.Development.json and appsetting.Production.json.
none.
=> Auto publicar posiciones twitter

Web/Views/Credits/Index.cshtml, Web/Views/Shared/_Layout.cshtml, Web/Views/Sponsors/Index.cshtml
- Fixed route issues for mustache in sponsors page and owl carousel
No visual aids
=> Fixed route issues for mustache in sponsors page and owl carousel

AppServices/Services/JobsService.cs, Data/EmpleaDbContext.cs, Domain/Framework/Constants/FeatureFlags.cs, Web/Framework/Configurations/AuthConfiguration.cs, Web/Program.cs, Web/Startup.cs
- Made changes to use Azure App Configuration and feature flags
=> Made changes to use Azure App Configuration and feature flags

AppServices/Services/TwitterService.cs, Web/Controllers/JobsController.cs, Web/Framework/Configurations/AuthConfiguration.cs, Web/Program.cs, Web/Startup.cs
- Made changes to use Azure App Configuration and feature flags.
|---|---|
|<img width="1162" alt="before" src="https://user-images.githubusercontent.com/2293759/68176843-ae6d8d00-ff5c-11e9-8978-a806c1cb9358.png"> | <img width="1158" alt="after" src="https://user-images.githubusercontent.com/2293759/68176875-c6dda780-ff5c-11e9-9c4f-bfdb7271fb17.png">|
=> Fixed App Configuration + Feature Flags

Web/Startup.cs, Web/Views/Shared/_Layout.cshtml, Web/Web.csproj, Web/appsettings.template.json
- Configured client side script inside of _Layout.cshtml
- Added an app.config section for Instrumentation Key
=> Added AppInsights to both server and client

Web/Views/Shared/_Footer.cshtml, Web/Web.csproj
- Added AssemvlyVersion Targuet in Web.csproj file
- Added display version in footer view file
> issue #102 
|---|---|
| ![Screenshot from 2020-02-09 13-02-51](https://user-images.githubusercontent.com/10536381/74106458-8bdfa700-4b3d-11ea-9e1b-68e414d5154b.png) |![Screenshot from 2020-02-09 13-09-15](https://user-images.githubusercontent.com/10536381/74106468-aa45a280-4b3d-11ea-9ba2-8ae4e6413273.png)|
=> Adding AssemblyVersion and version display in footer

Web/Controllers/JobsController.cs, Web/Views/UserProfile/_partials/ManageJobsView.cshtml
- Ajustes en controller de Jobs
- Ajustes en profile
=> Ajustes JobsController y ManageJobsView

Web/Framework/Configurations/AuthConfiguration.cs, Web/appsettings.template.json, readme.md
=> Adding feature flags evaluation to authentication

AppServices/Services/JobsService.cs, Web/Controllers/HomeController.cs, Web/Controllers/JobsController.cs, Web/ViewModels/HomeViewModel.cs, Web/Views/Home/Index.cshtml, Web/Views/Jobs/Index.cshtml, Web/wwwroot/js/site.js
#123 
- Solve problem with home page searching
- Solve problem with select2 placeholder and clear option
- Solve problems with lower case searching
No Visual Changes
=> 123 implement search view

Web/Views/Jobs/Index.cshtml
Se muestra un texto indicando que no existen registros para la busqieda
=> #131 Se creo la  condición cuando no existan registros para la consulta 

Web/Services/Slack/SlackService.cs, Web/Views/Jobs/Wizard.cshtml, Web/Views/Shared/_Layout.cshtml, Web/appsettings.template.json, Web/libman.json, Web/wwwroot/js/site.js
- Fixed slack service
- Fixed html editor
=> Fixed slack service and replaced html editor javascript

Web/Controllers/JobsController.cs
Added error log to job controller
=> Added error log to job controller

AppServices/Services/BaseService.cs
Logging inner exceptions from services
=> Logging inner exceptions from services

Domain/Entities/Job.cs, Web/Controllers/JobsController.cs, Web/Legacy/LegacyApiClient.cs, Web/Views/Jobs/Wizard.cshtml
- Added compliant label
- Added default values 
- Removed unused code
=> Added compliant label, added default values and removed unused code

Web/Controllers/JobsController.cs
- Fixed issue with publish date field not being assigned
=> Fixed issue with publish date field not being assigned

Domain/Entities/Location.cs, Web/ViewModels/WizardViewModel.cs
Fixed longitude and latitude data types
=> Fixed longitude and latitude data types

Web/Controllers/JobsController.cs, Web/Views/Home/Index.cshtml, Web/Views/Jobs/Wizard.cshtml, Web/Views/Jobs/_partials/JobResultItemView.cshtml, Web/Views/Jobs/_partials/LegacyJobResultItemView.cshtml
=> A bunch of stuff

Web/Controllers/JobsController.cs
- Delegated json parsing for slack payload to mvc framework
=> Delegated json parsing for slack payload to mvc framework

Web/Controllers/JobsController.cs, Web/Framework/RequestBodyInitializer.cs, Web/Startup.cs
=> Added logging of request body

Web/Controllers/JobsController.cs
=> Fixed compilation issue

Web/Controllers/JobsController.cs, Web/Framework/Extensions/HttpContextExtensions.cs
Fixing access to request body for slack endpoint
=> Fixing access to request body for slack endpoint

Web/Controllers/JobsController.cs
=> Protected from null reference

Web/Controllers/JobsController.cs, Web/Framework/Extensions/HttpContextExtensions.cs
Changed data type to form data
=> Changed data type to form data

Web/Controllers/JobsController.cs
=> Taking payload from form body

AppServices/Services/JobsService.cs, Web/Controllers/JobsController.cs, Web/Views/Jobs/Details.cshtml, Web/Views/Jobs/_partials/JobResultItemView.cshtml, Web/Views/Jobs/_partials/LegacyJobResultItemView.cshtml, Web/wwwroot/css/custom.css
- Added style to hire type and badge for remote jobs
- Fixed search results order
=> Fixed search results order

Web/Views/Jobs/_partials/JobResultItemView.cshtml, Web/Views/Jobs/_partials/LegacyJobResultItemView.cshtml
- Change "like" icon to `ti-thumb-up` in Job Listing
**PD:** The job listing already matches the desire layout, see the issue for more details.
| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/13991439/84585223-88a24380-addb-11ea-91a4-4a899a59f741.png)     | ![image](https://user-images.githubusercontent.com/13991439/84549269-979ece00-acd5-11ea-97dc-e73dee2114b4.png)     |
closes #107
=> Change like icon to `ti-thumb-up` in Job Listing

readme.md
- Add license section on the readme
=> Add license section on the readme.md

Web/Views/Jobs/_partials/JobResultItemView.cshtml
=> Fixed search result issue

Web/Startup.cs, Web/Views/Jobs/Index.cshtml
=>  Fixed minor issues

Web/Framework/Configurations/AuthConfiguration.cs, Web/Startup.cs, Web/Web.csproj
Fixed issue with authorization
=> Fixed issue with authorization

.well-known/microsoft-identity-association.json
- Added file to authenticate domain for microsoft
=> Added file to authenticate domain

.well-known/microsoft-identity-association.json
=> Moved .well-known folder

Web/wwwroot/.well-known/microsoft-identity-association.json
=> Added missing file

AppServices/Services/JobsService.cs, Web/Views/Home/Index.cshtml
Al buscar un trabajo támbien se utilizan los siguientes campos:
- Categoría [`Job.Category.Name`]
- Tipo de jornada [`Job.HireType.Name`]
- Nombre de la empresa [`Job.Company.Name`]
Se actualizó el placeholder del campo de búsqueda de la página de inicio.
| Before                                                                                                       | After                                                                                                     |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/13991439/87899785-40042880-ca20-11ea-84f1- …
=> Extiende campos de busqueda de trabajo

Domain/Domain.csproj, Migrations/Migrations.csproj, init.sh
Updated target versions for migration project
=> Updated target versions for migration project

Web/Controllers/JobsController.cs
- Elimina comentarios en JobsController
close #185
=> Elimina comentarios en JobsController

AppServices/Services/JobsService.cs, Web/Views/Home/Index.cshtml
Al buscar un trabajo támbien se utilizan los siguientes campos:
- **Ubicación** [`Job.Location.Name`]
Se actualizó el placeholder del campo de búsqueda de la página de inicio.
| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/13991439/88088930-33cfb680-cb59-11ea-963b-c76d5ecade25.png)     | ![image](https://user-images.githubusercontent.com/13991439/88088892-231f4080-cb59-11ea-88a8-4629bfaec9cf.png)    |
close #181
=> Busca empleo por ubicación

Web/Controllers/JobsController.cs, Web/Controllers/SponsorsController.cs, Web/Views/Shared/_Analytics.cshtml, Web/Views/Shared/_GoogleAnalytics.cshtml, Web/Views/Shared/_Layout.cshtml
- Added missing og:image parameter 
- Fixed sponsors links
=> Added missing og image parameter and fixed sponsors links

Web/Controllers/JobsController.cs
- Job view counter improved using cookie to validate visited jobs.
- Default Visual Studio code format added ( Ctrl k + Ctrl D ).
Closes #191
=> Feature/191 Job View Counter Enhancement

readme.md
Added badge for production build
=> Added badge for production build

Web/Controllers/AccountController.cs, Web/Controllers/BaseController.cs, Web/Framework/ApplicationUser.cs, Web/Framework/Configurations/AuthConfiguration.cs, Web/Framework/ViewPageBase.cs, Web/appsettings.Development.json
Added claim for userid to user claims
=> Added claim for userid to user claims

Web/Controllers/JobsController.cs, Web/Framework/ApplicationUser.cs
Added Isauthenticated flag to user profile
=> Added Isauthenticated flag to user profile

Web/Views/Jobs/Details.cshtml, Web/wwwroot/css/custom.css
- Fix white space and line break issues in job description and qualifications
Closes #193 
|---|---|
| ![Before](https://user-images.githubusercontent.com/9166182/88485778-96082d00-cf46-11ea-848c-fc5ec806bed5.png) | ![After](https://user-images.githubusercontent.com/9166182/88485811-de274f80-cf46-11ea-9e12-f1d27a5770c9.png) |
=> Fix white spaces on job details

readme.md
- Improve powered by section in README, now images are aligned in horizontal
| Before                                                                                                         | After                                                                                                          |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/13991439/88957021-3ecacb00-d26c-11ea-8f17-b11dce18474f.png) | ![image](https://user-images.githubusercontent.com/13991439/88956359-3e7e0000-d26b-11ea-8523-e0d8973b0640.png) |
close #209
=> Improve powered by section in README 

readme.md
- Link link para unirse a slack de emplea.do arreglado
=> Link link para unirse a slack de emplea.do arreglado

Web/Views/Jobs/_partials/JobResultItemView.cshtml
- Link updated with companies job history page address
|---|---|
| ![image](http://g.recordit.co/LCLRBbj7IJ.gif) | ![image](http://g.recordit.co/zxBmQsmI0b.gif) |
=> 206 Link imágenes en lista inicial de jobs genera un 404
